<?php
$act = $_GET['act'] ?? '/';

match ($act) {
    'admin' => (new AdminController())->index(),
    'tour_list' => (new AdminController())->showTours(),
    'addtour' => (new AdminController())->formaddtour(),
    'createtour' => (new AdminController())->createtour(),
    'uppdatetour' => (new AdminController())->uppdatetour($_GET['tour_id'] ?? null),
    'uppdatetour1' => (new AdminController())->uppdatetour1($_GET['tour_id'] ?? null),
    'chitiettour' => (new AdminController())->getAggregatedTourData($_GET['tour_id'] ?? null),
    'deletetour' => (new AdminController())->deletetour($_GET['tour_id'] ?? null),
    'diadiem' => (new AdminController())->diadiem($_GET['tour_id'] ?? null),
    'gan_diadiem' => (new AdminController())->gan_diadiem($_GET['tour_id'] ?? null),
    'luu_gan_diadiem' => (new AdminController())->luu_gan_diadiem($_GET['tour_id'] ?? null),
    'xoa_diadiem' => (new AdminController())->xoa_diadiem_tour($_GET['dia_diem_tour_id'] ?? null),
    'xoa_dia_diem' => (new AdminController())->xoa_dia_diem_tour($_GET['dia_diem_tour_id'] ?? null),
    'sua_diadiemtour' => (new AdminController())->sua_diadiem_tour($_GET['dia_diem_tour_id'] ?? null, $_GET['tour_id'] ?? null),
    'capnhat_diadiem_tour' => (new AdminController())->capnhat_diadiem_tour($_GET['dia_diem_tour_id'] ?? null),
    'ncc_list' => (new AdminController())->showncc(),
    'ncc_add' => (new AdminController())->formaddncc(),
    'ncc_create' => (new AdminController())->createncc(),
    'ncc_update' => (new AdminController())->formupdatencc($_GET['id'] ?? null),
    'ncc_update_save' => (new AdminController())->updatencc($_GET['id'] ?? null),
    'ncc_delete' => (new AdminController())->deletencc($_GET['id'] ?? null),
    'listlichtrinhtour' => (new AdminController())->listlichtrinhtour($_GET['tour_id'] ?? null),
    'addlichtrinh' => (new AdminController())->formAddLichTrinh($_GET['tour_id'] ?? null),
    'createlichtrinh' => (new AdminController())->createLichTrinh($_GET['tour_id'] ?? null),
    'editlichtrinh' => (new AdminController())->editLichTrinh($_GET['lich_trinh_id'] ?? null),
    'updatelichtrinh' => (new AdminController())->capnhatLichTrinh($_GET['lich_trinh_id'] ?? null),
    'deletelichtrinh' => (new AdminController())->deleteLichTrinh($_GET['lich_trinh_id'] ?? null),
    'hdv' => (new AdminController())->hdv(),
    'addhdv' => (new AdminController())->addHDV(),
    'createhdv' => (new AdminController())->createHDV(),
    'deletehdv' => (new AdminController())->deleteHDV($_GET['id'] ?? null),
    'edithdv' => (new AdminController())->editHDV($_GET['id'] ?? null),
    'updatehdv' => (new AdminController())->updateHDV($_GET['id'] ?? null),
    'chinhsach' => (new AdminController())->chinhsach($_GET['tour_id'] ?? null),
    'luu_chinh_sach_tour' => (new AdminController())->luuChinhSachTour($_GET['tour_id'] ?? null),
    'xoa_chinh_sach_tour' => (new AdminController())->xoaChinhSachTour($_GET['id'] ?? null),
    'dattourlist' => (new AdminController())->dattourlist(),
    'dat_tour_add' => (new AdminController())->dat_tour_add(),
    'dat_tour_save' => (new AdminController())->dat_tour_save(),
    'hanh_khach_add' => (new AdminController())->hanh_khach_add($_GET['dat_tour_id'] ?? null),
    //'dat_tour_detail' => (new AdminController())->dat_tour_detail($_GET['dat_tour_id'] ?? null),
    'hanh_khach_save' => (new AdminController())->hanh_khach_save($_GET['dat_tour_id'] ?? null),
    'dat_coc' => (new AdminController())->dat_coc($_GET['dat_tour_id'] ?? null),
    'dat_coc_save' => (new AdminController())->dat_coc_save($_GET['dat_tour_id'] ?? null),
    // 'hanhkhach_list' => (new AdminController())-> showHK(),
    'logout' => (new AdminController())->logout(),
    default => (new AdminController())->index(),
    
};
